### ISSUE TITLE
Need Releases Version

### ISSUE THREAD

**Issue by Small-Miao** [Incr3dible/20Clash#22]
i can't Build this project

**Comment by Incr3dible** [comment]
Any error for me?

**Comment by kashifkhan0336** [comment]
[20Clash-master.zip](https://github.com/Incr3dible/20Clash/files/4846623/20Clash-master.zip)
Here is the compiled version

**Comment by jakovmarkovanovic** [comment]
> i can't Build this project

Reliad packets
